language: c

sudo: false

matrix:
  fast_finish: true
  include:
    # macOS build
    - env: INSTALL_TYPE=develop FITS="astropy" TEST=submodule MATPLOTLIBVER=2 XSPECVER="12.10.1b" TRAVIS_PYTHON_VERSION="3.7"
      os: osx
    # Barebone build to check tests pass when most of the tests must be skipped.
    # We need to use TEST=none to remove the test-data submodule.
    - env: INSTALL_TYPE=develop TEST=none NUMPYVER=1.11 TRAVIS_PYTHON_VERSION="2.7"
    # Full build (including ds9 and xspec), Python 3.5, setup.py develop, astropy, matplotlib 2
    - env: XSPECVER="12.10.1b" NUMPYVER="1.11" FITS="astropy" INSTALL_TYPE=develop TEST=submodule MATPLOTLIBVER=2 TRAVIS_PYTHON_VERSION="3.5"
      sudo: required
      dist: trusty
    # As above, Python 3.6, setup.py install, xspec 12.10
    - env: XSPECVER="12.10.1b" NUMPYVER="1.11" FITS="astropy" INSTALL_TYPE=install TEST=submodule MATPLOTLIBVER=2 TRAVIS_PYTHON_VERSION="3.6"
      sudo: required
      dist: trusty
    # As above, python 3.7, numpy 1.15, matplotlib 3
    - env: XSPECVER="12.10.1b" NUMPYVER="1.15" FITS="astropy" INSTALL_TYPE=install TEST=submodule MATPLOTLIBVER=3 TRAVIS_PYTHON_VERSION="3.7"
      sudo: required
      dist: trusty
    # Experimental support for using Sphinx to build the documentation
    # should we not run tests with this build (to save time); i.e. have
    # a specific build just for the documentation and nothing else?
    - env: DOCS=true INSTALL_TYPE=build_sphinx TEST=none TRAVIS_PYTHON_VERSION="3.7"
      sudo: required
      dist: trusty
    # Install sherpatest package rather than relying on relative location of the submodule
    # Also, install matplotlib 2.0 and do not install astropy (checks tests are properly skipped)
    - env: INSTALL_TYPE=install TEST=package MATPLOTLIBVER=2 TRAVIS_PYTHON_VERSION="3.6"
    # Install astropy without matplotlib (checks tests are properly skipped)
    - env: INSTALL_TYPE=develop TEST=submodule FITS="astropy" TRAVIS_PYTHON_VERSION="3.5"
    # A relatively basic installation - NumPy and AstroPy - with no test data; this is similar to the preceeding
    # test, so perhaps could be combined?
    - env: INSTALL_TYPE=develop TEST=none FITS="astropy" TRAVIS_PYTHON_VERSION="3.5"

before_install:
  - source travis/setup_conda.sh

  # XSPEC and DS9
  - if [ -n "${XSPECVER}" ];
      then source travis/setup_xspec_ds9.sh;
    fi

  # Doc installation (try to use a similar same setup as on Read-The-Docs)
  - if [ "${DOCS}" == "true" ];
     then pip install --requirement docs/rtd-pip-requirements;
    fi
  
install:
    - python setup.py $INSTALL_TYPE

script:
  - source travis/test.sh

notifications:
  email:
    - olaurino@cfa.harvard.edu

